# Settings that the LAMMPS build will import when this package library is used
CUDA_FLAGS := -I/opt/nvidia/cudatoolkit/5.5.20-1.0402.7700.8.1/include -DUNIX  -DFFT_CUFFT -DCUDA_PRECISION=2 -DCUDA_ARCH=20 
CUDA_USRLIB_CONDITIONAL := -L/opt/nvidia/cudatoolkit/5.5.20-1.0402.7700.8.1/lib -L/opt/nvidia/cudatoolkit/5.5.20-1.0402.7700.8.1/lib64 -lcufft
 
user-cuda_SYSINC = ${CUDA_FLAGS}
user-cuda_SYSLIB = -lcuda -lcudart
user-cuda_SYSPATH = $(CUDA_USRLIB_CONDITIONAL)
